// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8aLMwFmWrYIgDcDEVj5i9_BW8GvRqz0',
    appId: '1:809771467523:web:b14e8829d1105ec87a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    authDomain: 'tech-8ee17.firebaseapp.com',
    storageBucket: 'tech-8ee17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xRI6UK4NZRQocj7HCpkeo4MULubJbKM',
    appId: '1:809771467523:android:bea00b08046e0c7c7a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKvlHDV-We8_eZB0iVb8ekzF_3z2LY-c',
    appId: '1:809771467523:ios:3b0c4c563e0305907a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.firebasestorage.app',
    iosBundleId: 'com.example.textile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMKvlHDV-We8_eZB0iVb8ekzF_3z2LY-c',
    appId: '1:809771467523:ios:3b0c4c563e0305907a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    storageBucket: 'tech-8ee17.firebasestorage.app',
    iosBundleId: 'com.example.textile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm-j9Rmnf3JCnofJvBMIzxKdeLLD9-NgE',
    appId: '1:809771467523:web:8d1eb99155ff2b3c7a9f36',
    messagingSenderId: '809771467523',
    projectId: 'tech-8ee17',
    authDomain: 'tech-8ee17.firebaseapp.com',
    storageBucket: 'tech-8ee17.firebasestorage.app',
  );
}
